<?php

/**
 * @file
 * Contains meetup_events_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function meetup_events_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the meetup_events_field module.
    case 'help.page.meetup_events_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a field type for entering meetup.com group name and displaying upcoming events') . '</p>';
      return $output;

    default:
  }
}
